### ISSUE TITLE
Kotlin generator assigns nullable refs to non-nullable variables in Java interop mode

### ISSUE THREAD

**Issue by oldergod** [square/wire#997]
We assign a [nullable](https://github.com/square/wire/blob/d9e9eb9c9f35aaceabc66a298ccf9131842072f5/wire-tests/src/test/proto-kotlin/com/squareup/wire/protos/kotlin/person/Person.kt.java.interop#L237) to a [non-nullable](https://github.com/square/wire/blob/d9e9eb9c9f35aaceabc66a298ccf9131842072f5/wire-tests/src/test/proto-kotlin/com/squareup/wire/protos/kotlin/person/Person.kt.java.interop#L253) here https://github.com/square/wire/blob/d9e9eb9c9f35aaceabc66a298ccf9131842072f5/wire-tests/src/test/proto-kotlin/com/squareup/wire/protos/kotlin/person/Person.kt.java.interop#L243

**Comment by Egorand** [comment]
The links are off after the recent changes. Can you please attach code snippets that manifest the issue?

**Comment by oldergod** [comment]
Sorry, look are bound to a sha now.

We define a [nullable `type` in `Person`](https://github.com/square/wire/blob/d9e9eb9c9f35aaceabc66a298ccf9131842072f5/wire-tests/src/test/proto-kotlin/com/squareup/wire/protos/kotlin/person/Person.kt.java.interop#L237), the [`Person.Builder.type` isn't nullable](https://github.com/square/wire/blob/d9e9eb9c9f35aaceabc66a298ccf9131842072f5/wire-tests/src/test/proto-kotlin/com/squareup/wire/protos/kotlin/person/Person.kt.java.interop#L253).

Compilation error happens in `Builder.build()` because we [assign the non-nullable to the nullable](https://github.com/square/wire/blob/d9e9eb9c9f35aaceabc66a298ccf9131842072f5/wire-tests/src/test/proto-kotlin/com/squareup/wire/protos/kotlin/person/Person.kt.java.interop#L243).

**Comment by Egorand** [comment]
Ah, I see, thanks! Looks the nullability is incorrect in the Builder.

**Comment by Egorand** [comment]
Related to broken treatment of fields with default values and fixed by #1023. 

Originally, if a message field had a default value, we were generating a field of a non-nullable type inside `Builder` and initializing it to the default value. The type of the setter's parameter for that field in `Builder` was still nullable - that was a bug. Now we treat fields with default values same as all other `Builder` fields, hence fields and setters always use nullable types (excluding `repeated` and `map` fields, for which we use empty collections as default values).
