### ISSUE TITLE
Redundant generated kotlin files taken into account

### ISSUE THREAD

**Issue by koral--** [square/wire#2299]
Steps to reproduce:
1. Have an Android project with multiple product flavors
2. Execute `compile<flavor 1>Kotlin` Gradle task where `<flavor 1>` is the name of the first product flavor
3. Execute `compile<flavor 2>Kotlin` Gradle task

Actual result:
The second invocation fails due to class declaration. That class is generated from `.proto` file.
Clean build works around the issue.

Expected result:
No compilation error.

Versions:
* wire: 4.4.0
* Gradle: 7.4.2
* Kotlin: 1.6.21
* Android Gradle plugin: 7.2.1

`.proto` file is located in the `main` source set, in a library project which has the same flavors as the app.
However, the generated `.kt` files land inside the flavor-specific directory (`build/source/wire/flavorN`).

The issue started occurring after updating wire from 4.3.0 to 4.4.0.

**Comment by oldergod** [comment]
Would it be possible to reproduce that with the samples we have in the repo?

**Comment by koral--** [comment]
Acknowledged. I'll try to check those samples.

**Comment by koral--** [comment]
I've compared my project with samples and found 2 additional elements in my code which are not present in the samples:
1. I have the sourcePath set in the `wire` block:

```
    sourcePath {
        srcDir 'src/main/proto'
    }
```
2. Inside the `android` block I have this:
```
    sourceSets {
        main.java.srcDirs += "$buildDir/generated/source/wire/"
    }
```
After removing them the issue has gone. So I'm closing this ticket.
